export const BRAND = {
  name: 'Rose Destiny',
  fullName: 'Rose Destiny Cleaning Services',
  tagline: 'Clean Spaces, Healthier Lives',
  email: 'admin@rosedestinycleaningservices.co.za',
  phone: '+27 73 947 5143',
  phoneDisplay: '073 947 5143',
  whatsappNumber: '27739475143',
  address: 'Johannesburg & surrounding areas',
  hours: 'Mon – Sat · 08:00 – 18:00',
  social: {
    instagram: 'https://www.instagram.com/rose_destinycleaningservices/',
    facebook: 'https://www.facebook.com/Rosedestiny1cleaningservices',
    pinterest: 'https://pinterest.com/rosedestiny',
    tiktok: 'https://tiktok.com/@rosedestiny',
  },
  currency: 'ZAR',
  currencySymbol: 'R',
  vatRate: 0.15,
  deliveryFlatFee: 120,
  freeDeliveryThreshold: 1500,
} as const;
