export const BRAND = {
  name: 'Rose Destiny',
  tagline: 'Luxury Florals, Hand-Tied with Grace',
  email: 'hello@rosedestiny.co.za',
  phone: '+27 (0)82 000 0000',
  whatsappNumber: '27820000000',
  address: 'Studio 14, Sandton, Johannesburg, South Africa',
  hours: 'Mon – Sat · 08:00 – 18:00',
  social: {
    instagram: 'https://instagram.com/rosedestiny',
    facebook: 'https://facebook.com/rosedestiny',
    pinterest: 'https://pinterest.com/rosedestiny',
    tiktok: 'https://tiktok.com/@rosedestiny',
  },
  currency: 'ZAR',
  currencySymbol: 'R',
  vatRate: 0.15,
  deliveryFlatFee: 120,
  freeDeliveryThreshold: 1500,
} as const;
